version: 2.1

commands:
    install_pnpm:
        steps:
            - run:
                  name: Install pnpm package manager
                  command: |
                      corepack enable
                      corepack prepare pnpm@latest-7 --activate
    restore_pnpm_cache:
        steps:
            - restore_cache:
                  name: Restore pnpm Package Cache
                  keys:
                      - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
    save_pnpm_cache:
        steps:
            - save_cache:
                  name: Save pnpm Package Cache
                  key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - node_modules
    save_build_cache:
        parameters:
            cache_key:
                type: string
        steps:
            - save_cache:
                  name: Save build cache
                  key: build-output-<< parameters.cache_key >>-{{ .Environment.CIRCLE_SHA1 }}
                  paths:
                      - build
    restore_build_cache:
        parameters:
            cache_key:
                type: string
        steps:
            - restore_cache:
                  name: Restore build cache
                  keys:
                      - build-output-<< parameters.cache_key >>-{{ .Environment.CIRCLE_SHA1 }}
    ylide_build:
        parameters:
            build_cmd:
                type: string
        steps:
            - run:
                  name: Build project
                  command: |
                      CI=false pnpm run << parameters.build_cmd >>
    ylide_store_artifacts:
        steps:
            - store_artifacts:
                  path: build
                  destination: build
    wrangler:
        parameters:
            project_name:
                type: string
        steps:
            - run:
                  name: Install Wrangler
                  command: |
                      npm install -g wrangler@2.12.0
            - run:
                  name: Upload build through Wrangler
                  command: |
                      wrangler pages publish build --project-name=<< parameters.project_name >>

jobs:
    install: # this can be any name you choose
        docker:
            - image: node:16

        steps:
            - checkout
            - restore_pnpm_cache
            - install_pnpm
            - run:
                  name: Install Dependencies
                  command: |
                      pnpm install
            - save_pnpm_cache
    build_hub:
        docker:
            - image: node:16
        steps:
            - checkout
            - restore_pnpm_cache
            - install_pnpm
            - ylide_build:
                  build_cmd: build-hub
            - save_build_cache:
                  cache_key: hub
            - ylide_store_artifacts
    deploy_hub:
        docker:
            - image: node:16
        steps:
            - restore_build_cache:
                  cache_key: hub
            - wrangler:
                  project_name: ylide-mail
    deploy_hub_staging:
        docker:
            - image: node:16
        steps:
            - restore_build_cache:
                  cache_key: hub
            - wrangler:
                  project_name: ylide-mail-staging
    build_airswap:
        docker:
            - image: node:16
        steps:
            - checkout
            - restore_pnpm_cache
            - install_pnpm
            - ylide_build:
                  build_cmd: build-airswap
            - save_build_cache:
                  cache_key: airswap
            - ylide_store_artifacts
    deploy_airswap:
        docker:
            - image: node:16
        steps:
            - restore_build_cache:
                  cache_key: airswap
            - wrangler:
                  project_name: ylide-otc-airswap
    build_1inch:
        docker:
            - image: node:16
        steps:
            - checkout
            - restore_pnpm_cache
            - install_pnpm
            - ylide_build:
                  build_cmd: build-1inch
            - save_build_cache:
                  cache_key: 1inch
            - ylide_store_artifacts
    deploy_1inch:
        docker:
            - image: node:16
        steps:
            - restore_build_cache:
                  cache_key: 1inch
            - wrangler:
                  project_name: ylide-otc-1inch
    build_paraswap:
        docker:
            - image: node:16
        steps:
            - checkout
            - restore_pnpm_cache
            - install_pnpm
            - ylide_build:
                  build_cmd: build-paraswap
            - save_build_cache:
                  cache_key: paraswap
            - ylide_store_artifacts
    deploy_paraswap:
        docker:
            - image: node:16
        steps:
            - restore_build_cache:
                  cache_key: paraswap
            - wrangler:
                  project_name: ylide-otc-paraswap

workflows:
    build_and_test:
        jobs:
            - install:
                  filters:
                      branches:
                          only:
                              - hub-release
                              - otc-release
                              - dev
            - build_hub:
                  requires:
                      - install
                  filters:
                      branches:
                          only:
                              - hub-release
                              - dev
            - deploy_hub:
                  requires:
                      - build_hub
                  filters:
                      branches:
                          only:
                              - hub-release
            - deploy_hub_staging:
                  requires:
                      - build_hub
                  filters:
                      branches:
                          only:
                              - dev
            - build_airswap:
                  requires:
                      - install
                  filters:
                      branches:
                          only:
                              - otc-release
            - deploy_airswap:
                  requires:
                      - build_airswap
                  filters:
                      branches:
                          only:
                              - otc-release
            - build_1inch:
                  requires:
                      - install
                  filters:
                      branches:
                          only:
                              - otc-release
            - deploy_1inch:
                  requires:
                      - build_1inch
                  filters:
                      branches:
                          only:
                              - otc-release
            - build_paraswap:
                  requires:
                      - install
                  filters:
                      branches:
                          only:
                              - otc-release
            - deploy_paraswap:
                  requires:
                      - build_paraswap
                  filters:
                      branches:
                          only:
                              - otc-release
