version: 2.1

jobs:
    build: # this can be any name you choose
        docker:
            - image: node:16

        steps:
            - checkout
            - restore_cache:
                  name: Restore pnpm Package Cache
                  keys:
                      - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install pnpm package manager
                  command: |
                      corepack enable
                      corepack prepare pnpm@latest-7 --activate
            - run:
                  name: Install Dependencies
                  command: |
                      pnpm install
            - save_cache:
                  name: Save pnpm Package Cache
                  key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
                  paths:
                      - node_modules
            - run:
                  name: Build project
                  command: |
                      CI=false pnpm run build-hub
            - save_cache:
                  key: build-output-{{ .Environment.CIRCLE_SHA1 }}
                  paths:
                      - build
            - store_artifacts:
                  path: build
                  destination: build
    deploy:
        docker:
            - image: node:16

        steps:
            - checkout
            - restore_cache:
                  name: Restore pnpm Package Cache
                  keys:
                      - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
            - run:
                  name: Install Wrangler
                  command: |
                      npm install -g wrangler@2.12.0
            - run:
                  name: Upload build through Wrangler
                  command: |
                      wrangler pages publish build --project-name=ylide-mail

workflows:
    build_and_test:
        jobs:
            - build
            - deploy
            # - test:
            #     requires:
            #       - build
            # - hold:
            #     type: approval
            #     requires:
            #       - build
            #       - test
            # - deploy:
            #     requires:
            #       - hold
